### ISSUE TITLE
Feedback and Discussion

### ISSUE THREAD

**Issue by rebaz36** [rebaz36/Portfolio#14]
## [Morning session: Peer-to-peer code review](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/morning-peer-to-peer-reviews.md)

- Code Feedback and Review
- Code Explaination
- Code Improvements feedback

**Comment by Apatakiti** [comment]
-**Optional**
 In the mobile session, part of the background images are hidden. You suggest you make them look be visible on the screen.

You have done a great job,👋 but I suggest you make the background images fit on the screen.

**Comment by rebaz36** [comment]
thanks for the feedback, i have solved this issue
